name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2.1.3

      - name: Install Yarn Package
        run: |
          sudo npm install --global yarn
          yarn info

      - name: Install NPM Packages
        run: yarn install

      - name: Create the ./build dir and copy package.json
        run: mkdir build & cp ./package.json ./build

      - name: Run Semantic Versioning Dummy
        run: yarn sem-ver