name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2.1.3

      - name: Install Yarn Package
        run: |
          sudo npm install --global yarn
          yarn info
      
      - name: Install NPM Packages
        run: yarn install
      
      - name: Run Semantic Versioning 
        run: yarn sem-ver
